In [1]:
import torch

In [2]:
z = torch.zeros(5,3)   #A 5x3 matrix filled with zeros
print(z)
print(z.dtype)    # Zeros are 32-bit floating point numbers (default PyTorch)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [3]:
i = torch.ones((5,3), dtype=torch.int16) # A 5x3 matrix filled up with ones, set data type is int16
print(i)
print(i.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


In [7]:
torch.manual_seed(1729)
r1 = torch.rand(2,2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2,2)
print('\nA different random tensor:')
print(r2)

torch.manual_seed(1729)
r3 = torch.rand(2,2)
print('\nShould match r1:')
print(r3)

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [11]:
ones = torch.ones(2,3)
print(ones)

twos = torch.ones(2,3)*2
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)

r1 = torch.rand(2,3)
r2 = torch.rand(2,3)
r3 = r1+r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


In [12]:
r = torch.rand(2,2) - 0.5*2   #values between -1 and 1
print('A random matrix, r:')
print(r)

#Common mathematical operations are supported 
print('\nAbsolute value of r:')
print(torch.abs(r))

#..as are in trigonometrical functions
print('\nInverse sine of r:')
print(torch.asin(r))

#and linear algebra operations
print('\nAnd Determinant of r:')
print(torch.det(r))
print('\nSingular value decompostions of r:')
print(torch.svd(r))

# and statistical and aggregate operations
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.1344, -0.4793],
        [-0.3135, -0.6386]])

Absolute value of r:
tensor([[0.1344, 0.4793],
        [0.3135, 0.6386]])

Inverse sine of r:
tensor([[-0.1348, -0.4999],
        [-0.3189, -0.6927]])

And Determinant of r:
tensor(-0.0645)

Singular value decompostions of r:
torch.return_types.svd(
U=tensor([[-0.5711, -0.8209],
        [-0.8209,  0.5711]]),
S=tensor([0.8651, 0.0745]),
V=tensor([[ 0.3862, -0.9224],
        [ 0.9224,  0.3862]]))

Average and standard deviation of r:
(tensor(0.2168), tensor(-0.3915))

Maximum value of r:
tensor(-0.1344)
